name: rig can view active development servers

on:
  push:
    branches: [ rig ]
  pull_request:
    branches: [ rig ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Add rig to $PATH
      run: echo "$(pwd)/bin" >> $GITHUB_PATH
      
    - name: Run rig --start-server
      run: rig --start-server
      
    - name: Run rig --view-active-servers
      run: rig --view-active-servers
